apiVersion: v1
kind: Pod
metadata:
  name: redis
  namespace: kube-ops
  labels:
    app: redis
spec:
  containers:
    - name: redis
      image: 'redis:6.2.1'
      command:
        - redis-server
        - /redis-conf/redis.conf
      env:
        - name: MASTER
          value: 'true'
      ports:
        - containerPort: 6379
      resources:
        limits:
          cpu: '0.1'
      volumeMounts:
        - mountPath: /data
          name: data
        - mountPath: /redis-conf
          name: config
    - name: redis-exporter
      image: oliver006/redis_exporter:latest
      resources:
        limits:
          cpu: 200m
          memory: 200Mi
        requests:
          cpu: 100m
          memory: 100Mi
      ports:
      - containerPort: 9121
  volumes:
    - name: data
      emptyDir: {}
    - name: config
      configMap:
        name: example-redis-config
        items:
          - key: redis-config
            path: redis.conf
  nodeSelector:
    app: prometheus
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: example-redis-config
  namespace: kube-ops
data:
  redis-config: |
    maxmemory 2mb
    maxmemory-policy allkeys-lru
    dir /data
    appendonly yes
    save 900 1
    save 300 10
    save 60 10000
---
apiVersion: v1
kind: Service
metadata:
  name: redis-master
  namespace: kube-ops
  labels:
    app: redis
spec:
  selector:
    app: redis
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
  - name: prom
    port: 9121
    targetPort: 9121
