apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager
  namespace: kube-ops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      labels:
        app: alertmanager
    spec:
      containers:
      - name: alertmanager
        image: prom/alertmanager:v0.19.0
        imagePullPolicy: IfNotPresent
        args:
        - "--config.file=/etc/alertmanager/config.yml"
        ports:
        - containerPort: 9093
          name: http
        volumeMounts:
        - mountPath: "/etc/alertmanager"
          name: alertcfg
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 100m
            memory: 256Mi
      nodeSelector:
        app: prometheus
      volumes:
    #   - name: alertcfg
    #     persistentVolumeClaim:
    #       claimName: alertmanager     # 使用prometheus 的 pvc
      - name: alertcfg
        configMap:
          name: alert-config
